CKEDITOR.addTemplates("default",{imagesPath:CKEDITOR.getUrl(CKEDITOR.plugins.getPath("templates")+"templates/images/"),
templates:[
	{title:"Responsiva a dos columnas",
	image:"template4.gif",
	description:"1 div a 100% y 2 divs dentro responsivas.",
	html:'<div style="width: 100%;"><h3>Encabezado H3</h3><div style="float:left;width:50%;text-align:left;min-height:60px;height:auto !important;height:60px;min-width: 50%;"><p>Escribir texto de Div 1 aquí</p></div><div style="float:left;width:50%;text-align:left;min-height:60px;height:auto !important;height:60px;min-width: 50%;"><p>Escribir texto de Div 2 aquí</p></div></div>'},
	{title:"Imagen y Encabezado",
	image:"template1.gif",
	description:"Una imagen principal y texto alrededor.",
	html:'<h3><img src=" " alt="" style="margin-right: 10px" height="100" width="100" align="left" />Encabezado H3</h3><p>Escribir texto aquí</p>'},
	{title:"Plantilla a dos columnas y fila abajo",
	image:"template2.gif",
	description:"Dos columnas y una fila debajo de ellas. Hecha con tabla.",
	html:'<table cellspacing="0" cellpadding="0" style="width:100%" border="0"><tr><td style="width:50%"><h3>Encabezado 1</h3></td><td></td><td style="width:50%"><h3>Encabezado 2</h3></td></tr><tr><td>Texto 1</td><td></td><td>Texto 2</td></tr></table><p>Más texto iría aquí.</p>'},
	{title:"Texto y Tabla",
	image:"template3.gif",
	description:"Encabezado seguido de tabla e imagen principal.",
	html:'<div style="width: 80%"><h3>Encabezado Principal</h3><table style="width:150px;float: right" cellspacing="0" cellpadding="0" border="1"><caption style="border:solid 1px black"><strong>Título de tabla</strong></caption><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></table><p>Introducir texto aquí</p></div>'},
	]});