<link href="<%=r%>web/lib/css/fuente.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/animate/animate.min.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/revo-slider/css/settings.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/cubeportfolio/css/cubeportfolio.min.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/owl-carousel/assets/owl.carousel.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/fancybox/jquery.fancybox.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/slider-for-bootstrap/css/slider.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/css/plugins.css" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/css/components.css" id="style_components" rel="stylesheet" type="text/css" /><link href="<%=r%>web/lib/app/css/default.css" rel="stylesheet" id="style_theme" type="text/css" /><link href="<%=r%>web/lib/css/custom.css" rel="stylesheet" type="text/css" />
<link rel="apple-touch-icon" sizes="180x180" href="http://www.cursit.com/web-demo/web/lib/img/favicones/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="http://www.cursit.com/web-demo/web/lib/img/favicones/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="http://www.cursit.com/web-demo/web/lib/img/favicones/favicon-16x16.png">
<link rel="manifest" href="http://www.cursit.com/web-demo/web/lib/img/favicones/site.json">
<link rel="mask-icon" href="http://www.cursit.com/web-demo/web/lib/img/favicones/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="http://www.cursit.com/web-demo/web/lib/img/favicones/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="http://www.cursit.com/web-demo/web/lib/img/favicones/browserconfig.xml">
<meta name="theme-color" content="#ffffff">